[package]
name = "save"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
bytemuck = { version = "1.24.0" }
bytemuck_derive = "1.10.2"
raw_bytes_container = { path = "../raw_bytes_container" }
packed_struct_container = { path = "../packed_struct_container" }
sha2 = "0.10.9"
