name: MFT CI

on:
  push:
    paths:
      - "mft/**"
      - ".github/workflows/mft.yml"
  pull_request:
    paths:
      - "mft/**"

jobs:
  build:
    name: Build & Test mft
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mft

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v2
        with:
          rust-version: stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build crate
        run: cargo build --all-targets

      - name: Build examples
        run: cargo build --examples

      - name: Run tests
        run: cargo test --all-targets

      - name: Run examples (optional)
        run: |
          if [ -d examples ]; then
            echo "Running examples..."
            for example in examples/*.rs; do
              exename=$(basename "${example%.rs}")
              cargo run --example "$exename" --quiet || exit 1
            done
          fi

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Lint with Clippy
        run: cargo clippy --all-targets -- -D warnings
