name: Packed Bits Container CI

on:
  push:
    paths:
      - "packed_bits_container/**"
      - ".github/workflows/packed_bits_container.yml"
  pull_request:
    paths:
      - "packed_bits_container/**"
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run fmt check
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build crate and examples
        run: cargo build --package mtf_api --examples

      - name: Run tests
        run: cargo test --package mtf_api --all-features