[package]
name = "packed_structs"
version = "0.1.0"
edition = "2024"

[dependencies]
#packed_struct_container = { path = "../packed_struct_container" }
bytemuck = { version = "1.24.0" }
bytemuck_derive = "1.10.2"
